version: "3.9"

services:
  backend:
    container_name: carpet_back
    build:
      context: .
      dockerfile: docker/Dockerfile.back
    volumes:
      - .:/carpet_market
    env_file: .env
    command: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8088"
    depends_on:
      - db_postgres
    networks:
      - app_network
    restart: always

  db_postgres:
    container_name: db_postgres
    image: postgres:16.2-alpine
    restart: unless-stopped
    env_file: .env
    networks:
      - app_network
    volumes:
      - carpet_market_db:/var/lib/postgresql/data/

    nginx_test:
      container_name: nginx_test
      build:
        context: .
        dockerfile: docker/Dockerfile.back.nginx
      env_file: .env
      ports:
        - "8080:8080"
      volumes_from:
        - backend
      volumes:
        - static:/static/
      restart: always
      networks:
        - app_network_test
      links:
        - backend
      depends_on:
        - backend
        - db_postgres