[tool.poetry]
name = "carpet-market"
version = "0.1.0"
description = ""
authors = ["Сократ"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.0"
sqlalchemy = {version = "^2.0.35", extras = ["asyncio"]}
alembic = "^1.13.3"
pydantic = "^2.9.2"
dishka = "^1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
