"""new tables structure v2

Revision ID: fde261b54265
Revises: f8620ac80deb
Create Date: 2025-01-13 15:24:45.627963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fde261b54265'
down_revision: Union[str, None] = 'f8620ac80deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('image_paths', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pile_structure', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'image_paths')
    op.drop_column('users', 'pile_structure')
    op.drop_column('users', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('pile_structure', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('image_paths', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_table('patterns')
    # ### end Alembic commands ###
