"""new tables structure v3

Revision ID: d12c4ea5f70b
Revises: fde261b54265
Create Date: 2025-01-13 15:31:07.338896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12c4ea5f70b'
down_revision: Union[str, None] = 'fde261b54265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpets', sa.Column('title', sa.String(), nullable=True))
    op.add_column('carpets', sa.Column('description', sa.String(), nullable=True))
    op.add_column('carpets', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('carpets', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('carpets', sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('carpets', sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('carpets', sa.Column('stock_amount', sa.Integer(), nullable=True))
    op.add_column('carpets', sa.Column('main_image_path', sa.String(), nullable=True))
    op.drop_column('carpets', 'last_name')
    op.drop_column('carpets', 'is_active')
    op.drop_column('carpets', 'telegram_username')
    op.drop_column('carpets', 'phone_number')
    op.drop_column('carpets', 'email')
    op.drop_column('carpets', 'first_name')
    op.drop_column('carpets', 'telegram_id')
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('users', 'retail_price')
    op.drop_column('users', 'title')
    op.drop_column('users', 'stock_amount')
    op.drop_column('users', 'main_image_path')
    op.drop_column('users', 'description')
    op.drop_column('users', 'width')
    op.drop_column('users', 'base_price')
    op.drop_column('users', 'height')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('main_image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('stock_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('retail_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'email')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('carpets', sa.Column('telegram_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carpets', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carpets', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carpets', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carpets', sa.Column('telegram_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carpets', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('carpets', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('carpets', 'main_image_path')
    op.drop_column('carpets', 'stock_amount')
    op.drop_column('carpets', 'retail_price')
    op.drop_column('carpets', 'base_price')
    op.drop_column('carpets', 'height')
    op.drop_column('carpets', 'width')
    op.drop_column('carpets', 'description')
    op.drop_column('carpets', 'title')
    # ### end Alembic commands ###
